server:
  port: 8088
spring:
  application:
    name: yogurt-learn
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/yogurtlearn
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    #最大连接数
    maxActive: 20
    initialSize: 1
    #超时等待时间以毫秒为单位
    maxWait: 60000
    #最小空闲连接
    minIdle: 1
    #timeBetweenEvictionRunsMillis,minEvictableIdleTimeMillis 他们两个配合，可以持续更新连接池中的连接对象，
    #当 timeBetweenEvictionRunsMillis 大于0时，每过timeBetweenEvictionRunsMillis 时间，
    #就会启动一个线程，校验连接池中闲置时间超过minEvictableIdleTimeMillis的连接对象。
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    #用于验证连接是否成功的查询SQL语句，SQL语句必须至少要返回一行数据
    validationQuery: select 'x'
    #testOnBorrow取得连接、testOnReturn返回连接,testWhileIdle连接空闲时 是否进行有效性验证
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    #redis 库号
    database: 0
    # 连接超时时间，单位 ms（毫秒）
    timeout: 3200
    # 连接池中的最大空闲连接
    pool.max-idle: 8
    # 连接池中的最小空闲连接
    pool.min-idle: 1
    #最大连接数
    pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: -1

#mybatis配置
mybatis:
  # 搜索指定包别名 （实体类所在的位置） ** 可以匹配多级目录。请自行节约一下
  typeAliasesPackage: com.**.entity
  #配置SQL映射文件路径
  mapper-locations: classpsth:mapper/*.xml
  #配置别名
  #type-aliases-package: com.zzf.springboot.model
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true

# Sql日志输出
logging:
  level:
    com:
      example:
        databasedemo:
          dao: trace # Dao层所在包。此包下通常是 *Mapper.java 或 *Dao.java
          # com.example.databasedemo.dao 是包名。
